insert into question (dificultad, pregunta, respuesta) values ('intermedio', 'def funcion(n):\n\treturn 1 if n == 0 else n * funcion(n - 1)\n\nresultado = funcion(5)\nprint(resultado)', '120');
insert into question (dificultad, pregunta, respuesta) values ('intermedio', 'palabra = "reconocer"\n\nes_palindromo = palabra == palabra[::-1]\nprint("Es palíndromo" if es_palindromo else "No es palíndromo")', 'Es palíndromo');
insert into question (dificultad, pregunta, respuesta) values ('básico', 'print("¡Hola, mundo!")', '¡Hola, mundo!');
insert into question (dificultad, pregunta, respuesta) values ('avanzado', 'import math\n\nnumeros = [10, 5, 8, 12, 7]\n\npromedio = sum(numeros) / len(numeros)\ndesviacion_estandar = math.sqrt(sum((x - promedio) ** 2 for x in numeros) / len(numeros))\n\nprint(f"Promedio: {promedio}, Desviación Estándar: {desviacion_estandar}")', 'Promedio: 8.4, Desviación Estándar: 2.588435821132085');
insert into question (dificultad, pregunta, respuesta) values ('avanzado', 'def funcion(oracion):\n\treturn '' ''.join(oracion.split()[::-1])\n\noracion_invertida = invertir_oracion("Python es genial")\nprint(oracion_invertida)', 'genial es Python');
insert into question (dificultad, pregunta, respuesta) values ('avanzado', 'lista1 = [1, 2, 3, 4, 5]\nlista2 = [3, 4, 5, 6, 7]\ninterseccion = list(set(lista1) & set(lista2))\nprint(interseccion)', '[3, 4, 5]');
insert into question (dificultad, pregunta, respuesta) values ('básico', 'numero = 5\ncuadrado = numero * numero\nprint(cuadrado)', '25');
insert into question (dificultad, pregunta, respuesta) values ('básico', 'num1 = 3\nnum2 = 7\nsuma = num1 + num2\nprint(suma)', '10');
insert into question (dificultad, pregunta, respuesta) values ('básico', 'numero = 10\nprint("Par" if numero % 2 == 0 else "Impar")', 'Par');
insert into question (dificultad, pregunta, respuesta) values ('básico', 'numeros = [1, 2, 3, 4, 5]\nprint(numeros)', '[1, 2, 3, 4, 5]');
insert into question (dificultad, pregunta, respuesta) values ('intermedio', 'base = 8\naltura = 5\narea = 0.5 * base * altura\nprint(area)','20.0');
insert into question (dificultad, pregunta, respuesta) values ('intermedio', 'import math\n\nradio = 5\narea = math.pi * radio ** 2\nprint(area)','78.53981633974483');
insert into question (dificultad, pregunta, respuesta) values ('intermedio', 'def fibonacci(n): return n if n <= 1 else fibonacci(n - 1) + fibonacci(n - 2)\nfibonacci(3)','5');
insert into question (dificultad, pregunta, respuesta) values ('avanzado', 'primos = [num for num in range(2, 50) if all(num % i != 0 for i in range(2, int(num ** 0.5) + 1))]\nprint(primos)', '[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]');
insert into question (dificultad, pregunta, respuesta) values ('avanzado', 'def funcion(n, r):\n\treturn 1 if r == 0 else funcion(n, r-1) * (n-r+1) // r\n\nresultado = funcion(5, 2)\nprint(resultado)', '10');
